# Funding information for OmniTrade AI
# Uncomment and configure if you want to accept sponsorships

# github: [yourusername]
# patreon: yourusername
# open_collective: omnitrade
# ko_fi: yourusername
# custom: ['https://yourwebsite.com/donate']
